version: '3.6'
services:
  broker-rabbitmq:
    image: "rabbitmq:3.10.5"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
  postgres:
    image: "postgres:12"
    ports:
    - "5434:5432"
    restart: always
    volumes:
      - db_data:/Users/justyn/flask-deploy/data/db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
  migration:
    build: .
    environment:
      - APP_ENV=${APP_ENV}
    command: flask db upgrade
    depends_on:
      - "postgres"
  api:
    build: .
    ports:
     - "6969:5000"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - "broker-rabbitmq"
      - "postgres"
      - "migration"
  api-worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - "broker-rabbitmq"
      - "postgres"
      - "migration"
  api-beat:
    build: .
    command: celery -A tasks.celery beat --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - "broker-rabbitmq"
      - "postgres"
      - "migration"

volumes:
  db_data: